### ISSUE TITLE
files is a whitelist should be documented

### ISSUE THREAD

**Issue by cfjedimaster** [zeit/now-cloud#40]
In the docs (https://zeit.co/docs/features/configuration), the fact that files is a whitelist is not documented. It implies you can use it to force a file blocked by .gitignore, but it doesn't make it clear you need to include everything else as well.

**Comment by davidkaneda** [comment]
Agreed, and would also question the behavior... would be nice if it was a way (or if there were some way) to just add files to the distro. ie. I build frontend assets into a `public` dir, but feels slightly odd I'd have to whitelist my `index.js`, `routes`, `lib`, `views`, etc. in order to upload public with it.

While on the subject, does now recognize any sort of npm `pre-publish` or similar in package.json? Something so that I can have it build minified files (locally, via devDependencies), when I run `now`?

Realize I could just do a `"deploy": "gulp build-min && now"`-type npm script, but just asking out of curiosity :) Thanks!

**Comment by sergiodxa** [comment]
Is already documented.

@davidkaneda the behavior match the files key in package.json when publishing to npm. We don't recognize any sort npm script in package.json, you can create a `deploy` script which runs `now` and then add a `predeploy` script.
